name: Run Kitchen Tests
on:
  push:
    branches:
      - kitchen

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 0.15.5

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: DWP Kitchen Terraform
      uses: dwp/github-action-kitchen-terraform@0.14.7
      with:
        kitchen-command: "test aws"
