name: Run Kitchen Tests
on:
  push:
    branches:
      - kitchen

jobs:
  kitchen:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v1.0.0
      with:
        terraform_version: 0.15.5
        
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: run kitchen command
      uses: lzysh/github-kitchen-terraform-action@v1.0.0
      with:
        kitchen-command: "converge aws"
