name: Run Kitchen Tests
on:
  push:
    branches:
      - kitchen

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: lzysh/github-kitchen-terraform-action@v1.0.0
      with:
        kitchen-command: "help"
